export default {
  siteName: 'Andrey Salomatin',
  blogName: `Living structure`,
  blogTitle: `Living structure – Blog by @flpvsk`,
  twitterLink: 'https://twitter.com/flpvsk',
  githubLink: 'https://github.com/flpvsk',
  emailLink: 'mailto:hello@flpvsk.com',
  hostName: 'flpvsk.com',
  host: 'https://flpvsk.com',
  posts: [
    {
      title: 'Open-sourcing the Meetup',
      heading: 'Open-sourcing the\u00A0Meetup',
      path: `/blog/2018-12-23-open-sourcing-the-meetup`,
      publishDate: '2018-12-23',
      author: 'Andrey Salomatin',
      description: `Increasingly meetups are dependent on platforms like Meetup.com and Facebook. Is it the best option? Let’s imagine an open-source version of meetup software.`,
    },
    {
      title: 'Making products under uncertainty',
      heading: 'Making products under\u00A0uncertainty',
      path: `/blog/2018-08-02-making-products-under-uncertainty`,
      publishDate: '2018-08-02',
      author: 'Andrey Salomatin',
      description: `Sometimes it’s clear what we need to build. Sometimes not at all. How should our approach to building products change when dealing with uncertainty?`,
    },
    {
      title: 'Theory of Constraints in Colour',
      heading: `Theory of\u00A0Constraints in\u00A0Colour`,
      path: `/blog/2018-02-16-theory-of-constraints-in-colour`,
      publishDate: '2018-02-16',
      author: 'Andrey Salomatin',
      description: `There are thousands of possible reasons for a piece of software to not perform well. Thousands. How many ways do we have of finding and fixing those issues? One.`,
    },
    {
      title: `Kanban like it's 1984`,
      heading: `Kanban like it’s 1984`,
      publishDate: '2017-12-11',
      author: 'Andrey Salomatin',
      path: `/blog/2017-12-11-kanban-like-it-is-1984`,
      description: `Everything was better in the 80s, so let’s go back in time for a minute. Imagine you are a worker at a car plant. What would your day look like?`,
    },
  ],
};
